name: Code Quality

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: 3.13
          enable-cache: true
          cache-suffix: uv-${{ runner.os }}-3.13

      - name: Install dependecies
        run: uv sync --all-groups

  ruff:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: 3.13
          enable-cache: true
          cache-suffix: uv-${{ runner.os }}-3.13

      - name: Install dependecies
        run: uv sync --all-groups

      - name: Run ruff
        run: |
          uv run ruff check .

  mypy:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: 3.13
          enable-cache: true
          cache-suffix: uv-${{ runner.os }}-3.13

      - name: Install dependecies
        run: uv sync --all-groups

      - name: Run mypy
        run: |
          uv run mypy --strict .
